allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  argon2: true
  esbuild: true
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@eslint/eslintrc@3.3.7'
  - globals@17.12.0
