export const ERROR_CODES = {
    BAD_REQUEST: 'BAD_REQUEST',
    CONFLICT: 'CONFLICT',
    FORBIDDEN: 'FORBIDDEN',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    INVALID_RELATION: 'INVALID_RELATION',
    NOT_FOUND: 'NOT_FOUND',
    MUST_CHANGE_PASSWORD: 'MUST_CHANGE_PASSWORD',
    PRISMA_VALIDATION_ERROR: 'PRISMA_VALIDATION_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',
    UNIQUE_CONSTRAINT: 'UNIQUE_CONSTRAINT',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    VALUE_TOO_LONG: 'VALUE_TOO_LONG',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
