export type PermissionSeed = {
    code: string;
    name: string;
    description: string;
};

export const PERMISSION_CATALOG = [
    { code: 'organizations.create', name: 'Crear organización', description: 'Permite crear una organización.' },
    { code: 'organizations.read-list', name: 'Listar organizaciones', description: 'Permite consultar el listado de organizaciones.' },
    { code: 'organizations.read-one', name: 'Ver organización', description: 'Permite consultar el detalle de una organización.' },
    { code: 'organizations.update', name: 'Actualizar organización', description: 'Permite actualizar una organización.' },
    { code: 'organizations.delete', name: 'Eliminar organización', description: 'Permite eliminar una organización.' },
    { code: 'organizations.members.read', name: 'Listar miembros de organización', description: 'Permite consultar los miembros de una organización.' },
    { code: 'organizations.members.add', name: 'Agregar miembro a organización', description: 'Permite agregar miembros a una organización.' },
    { code: 'organizations.members.remove', name: 'Remover miembro de organización', description: 'Permite remover miembros de una organización.' },
    { code: 'companies.create', name: 'Crear empresa', description: 'Permite crear empresas operativas.' },
    { code: 'companies.read-list', name: 'Listar empresas', description: 'Permite consultar el listado de empresas operativas.' },
    { code: 'companies.read-one', name: 'Ver empresa', description: 'Permite consultar el detalle de una empresa operativa.' },
    { code: 'companies.update', name: 'Actualizar empresa', description: 'Permite actualizar empresas operativas.' },
    { code: 'companies.delete', name: 'Inactivar empresa', description: 'Permite inactivar empresas operativas.' },
    { code: 'sub-companies.create', name: 'Crear subempresa', description: 'Permite crear subempresas.' },
    { code: 'sub-companies.read-list', name: 'Listar subempresas', description: 'Permite consultar el listado de subempresas.' },
    { code: 'sub-companies.read-one', name: 'Ver subempresa', description: 'Permite consultar el detalle de una subempresa.' },
    { code: 'sub-companies.update', name: 'Actualizar subempresa', description: 'Permite actualizar subempresas.' },
    { code: 'sub-companies.delete', name: 'Inactivar subempresa', description: 'Permite inactivar subempresas.' },
    { code: 'drivers.create', name: 'Crear conductor', description: 'Permite crear conductores.' },
    { code: 'drivers.read-list', name: 'Listar conductores', description: 'Permite consultar el listado de conductores.' },
    { code: 'drivers.read-one', name: 'Ver conductor', description: 'Permite consultar el detalle de un conductor.' },
    { code: 'drivers.update', name: 'Actualizar conductor', description: 'Permite actualizar conductores.' },
    { code: 'drivers.delete', name: 'Inactivar conductor', description: 'Permite inactivar conductores.' },
    { code: 'fuels.create', name: 'Crear combustible', description: 'Permite crear combustibles.' },
    { code: 'fuels.read-list', name: 'Listar combustibles', description: 'Permite consultar el listado de combustibles.' },
    { code: 'fuels.read-one', name: 'Ver combustible', description: 'Permite consultar el detalle de un combustible.' },
    { code: 'fuels.update', name: 'Actualizar combustible', description: 'Permite actualizar combustibles.' },
    { code: 'fuels.delete', name: 'Inactivar combustible', description: 'Permite inactivar combustibles.' },
    { code: 'vehicles.create', name: 'Crear vehículo', description: 'Permite crear vehículos.' },
    { code: 'vehicles.read-list', name: 'Listar vehículos', description: 'Permite consultar el listado de vehículos.' },
    { code: 'vehicles.read-one', name: 'Ver vehículo', description: 'Permite consultar el detalle de un vehículo.' },
    { code: 'vehicles.update', name: 'Actualizar vehículo', description: 'Permite actualizar vehículos.' },
    { code: 'vehicles.delete', name: 'Inactivar vehículo', description: 'Permite inactivar vehículos.' },
    { code: 'cards.create', name: 'Crear tarjeta', description: 'Permite crear tarjetas.' },
    { code: 'cards.read-list', name: 'Listar tarjetas', description: 'Permite consultar el listado de tarjetas.' },
    { code: 'cards.read-one', name: 'Ver tarjeta', description: 'Permite consultar el detalle de una tarjeta.' },
    { code: 'cards.update', name: 'Actualizar tarjeta', description: 'Permite actualizar tarjetas.' },
    { code: 'cards.delete', name: 'Inactivar tarjeta', description: 'Permite inactivar tarjetas.' },
    { code: 'stations.create', name: 'Crear estación', description: 'Permite crear estaciones.' },
    { code: 'stations.read-list', name: 'Listar estaciones', description: 'Permite consultar el listado de estaciones.' },
    { code: 'stations.read-one', name: 'Ver estación', description: 'Permite consultar el detalle de una estación.' },
    { code: 'stations.update', name: 'Actualizar estación', description: 'Permite actualizar estaciones.' },
    { code: 'stations.delete', name: 'Inactivar estación', description: 'Permite inactivar estaciones.' },
    { code: 'station-fuels.create', name: 'Crear combustible de estación', description: 'Permite asociar combustibles a estaciones.' },
    { code: 'station-fuels.read-list', name: 'Listar combustibles de estación', description: 'Permite consultar combustibles asociados a estaciones.' },
    { code: 'station-fuels.read-one', name: 'Ver combustible de estación', description: 'Permite consultar el detalle de un combustible de estación.' },
    { code: 'station-fuels.update', name: 'Actualizar combustible de estación', description: 'Permite actualizar combustibles de estación.' },
    { code: 'station-fuels.delete', name: 'Inactivar combustible de estación', description: 'Permite inactivar combustibles de estación.' },
    { code: 'cardcloud-card-stock.create', name: 'Crear tarjeta Cardcloud', description: 'Permite crear registros de tarjetas Cardcloud.' },
    { code: 'cardcloud-card-stock.read-list', name: 'Listar tarjetas Cardcloud', description: 'Permite consultar tarjetas Cardcloud.' },
    { code: 'cardcloud-card-stock.read-one', name: 'Ver tarjeta Cardcloud', description: 'Permite consultar el detalle de una tarjeta Cardcloud.' },
    { code: 'cardcloud-card-stock.update', name: 'Actualizar tarjeta Cardcloud', description: 'Permite actualizar tarjetas Cardcloud.' },
    { code: 'cardcloud-card-stock.delete', name: 'Inactivar tarjeta Cardcloud', description: 'Permite inactivar tarjetas Cardcloud.' },
    { code: 'users.create', name: 'Crear usuario', description: 'Permite crear un usuario desde el endpoint administrativo.' },
    { code: 'users.read-list', name: 'Listar usuarios', description: 'Permite consultar el listado de usuarios.' },
    { code: 'users.read-one', name: 'Ver usuario', description: 'Permite consultar el detalle de un usuario.' },
    { code: 'users.update', name: 'Actualizar usuario', description: 'Permite actualizar los datos de un usuario.' },
    { code: 'users.delete', name: 'Eliminar usuario', description: 'Permite eliminar un usuario.' },
    { code: 'users.access.assign', name: 'Asignar accesos a usuario', description: 'Permite asignar roles y scopes a un usuario.' },
    { code: 'users.access.read', name: 'Ver accesos de usuario', description: 'Permite consultar los accesos asignados a un usuario.' },
    { code: 'users.permissions.read', name: 'Ver permisos de usuario', description: 'Permite consultar los permisos efectivos de un usuario.' },
    { code: 'users.password.update', name: 'Cambiar contraseña de usuario', description: 'Permite cambiar la contraseña de un usuario.' },
    { code: 'users.2fa.unlink', name: 'Desvincular 2FA de usuario', description: 'Permite desvincular la configuración 2FA de un usuario.' },
    { code: 'users.credentials.resend', name: 'Reenviar credenciales de usuario', description: 'Permite regenerar y reenviar credenciales de acceso a un usuario.' },
    { code: 'roles.create', name: 'Crear rol', description: 'Permite crear un rol.' },
    { code: 'roles.read-list', name: 'Listar roles', description: 'Permite consultar el listado de roles.' },
    { code: 'roles.read-one', name: 'Ver rol', description: 'Permite consultar el detalle de un rol.' },
    { code: 'roles.update', name: 'Actualizar rol', description: 'Permite actualizar un rol.' },
    { code: 'roles.delete', name: 'Eliminar rol', description: 'Permite eliminar un rol.' },
    { code: 'roles.permissions.assign', name: 'Asignar permisos a rol', description: 'Permite asignar o sincronizar permisos en un rol.' },
    { code: 'roles.permissions.read', name: 'Ver permisos de rol', description: 'Permite consultar los permisos asignados a un rol.' },
    { code: 'permissions.create', name: 'Crear permiso', description: 'Permite crear un permiso.' },
    { code: 'permissions.read-list', name: 'Listar permisos', description: 'Permite consultar el listado de permisos.' },
    { code: 'permissions.read-one', name: 'Ver permiso', description: 'Permite consultar el detalle de un permiso.' },
    { code: 'permissions.update', name: 'Actualizar permiso', description: 'Permite actualizar un permiso.' },
    { code: 'permissions.delete', name: 'Eliminar permiso', description: 'Permite eliminar un permiso.' },
    { code: 'documents.create', name: 'Crear documento', description: 'Permite cargar un documento.' },
    { code: 'documents.read-list', name: 'Listar documentos', description: 'Permite consultar el listado de documentos.' },
    { code: 'documents.read-one', name: 'Ver documento', description: 'Permite consultar el detalle de un documento.' },
    { code: 'documents.download', name: 'Descargar documento', description: 'Permite descargar un documento.' },
    { code: 'documents.update', name: 'Actualizar documento', description: 'Permite actualizar los metadatos de un documento.' },
    { code: 'documents.delete', name: 'Eliminar documento', description: 'Permite eliminar un documento.' },
    { code: 'notifications.create', name: 'Crear notificación', description: 'Permite crear una notificación.' },
    { code: 'notifications.read-list', name: 'Listar notificaciones', description: 'Permite consultar la bandeja de notificaciones.' },
    { code: 'notifications.unread-count.read', name: 'Ver contador de no leídas', description: 'Permite consultar el contador de notificaciones no leídas.' },
    { code: 'notifications.mark-read', name: 'Marcar notificación como leída', description: 'Permite marcar una notificación como leída.' },
    { code: 'notifications.mark-read-all', name: 'Marcar todas las notificaciones como leídas', description: 'Permite marcar todas las notificaciones como leídas.' },
] as const satisfies PermissionSeed[];

export type PermissionCode = (typeof PERMISSION_CATALOG)[number]['code'];

export const ALL_PERMISSION_CODES = PERMISSION_CATALOG.map((permission) => permission.code);
