export type CapabilityRequirement = {
    all?: string[];
    any?: string[];
    authenticated?: true;
};

export type SidebarCapabilityDefinition = CapabilityRequirement & {
    label: string;
    path: string;
    section: 'inicio' | 'administracion' | 'operacion' | 'cardcloud' | 'tarjetahabiente' | 'documentos';
};

export type ModuleCapabilityDefinition = {
    canEnter: CapabilityRequirement;
    permissions: string[];
    actions: Record<string, CapabilityRequirement>;
};

export const SIDEBAR_CAPABILITIES = {
    dashboard: { label: 'Inicio', path: '/dashboard', section: 'inicio', authenticated: true },
    users: { label: 'Usuarios', path: '/administration/users', section: 'administracion', all: ['users.module'] },
    roles: { label: 'Roles', path: '/administration/roles', section: 'administracion', all: ['roles.module'] },
    permissions: { label: 'Permisos', path: '/administration/permissions', section: 'administracion', all: ['permissions.module'] },
    companies: { label: 'Compañías', path: '/administration/companies', section: 'administracion', all: ['companies.module'] },
    subCompanies: { label: 'Subcompañías', path: '/administration/sub-companies', section: 'administracion', all: ['sub-companies.module'] },
    drivers: { label: 'Conductores', path: '/operation/drivers', section: 'operacion', all: ['drivers.module'] },
    vehicles: { label: 'Vehículos', path: '/operation/vehicles', section: 'operacion', all: ['vehicles.module'] },
    cards: { label: 'Tarjetas', path: '/operation/cards', section: 'operacion', all: ['cards.module'] },
    fuels: { label: 'Combustibles', path: '/operation/fuels', section: 'operacion', all: ['fuels.module'] },
    stations: { label: 'Estaciones', path: '/operation/stations', section: 'operacion', all: ['stations.module'] },
    cardcloudAccount: { label: 'Cuenta', path: '/cardcloud/account', section: 'cardcloud', all: ['cardcloud.account.read-one'] },
    cardcloudStock: { label: 'Stock', path: '/cardcloud/stock', section: 'cardcloud', all: ['cardcloud-stock.module'] },
    cardcloudSubaccounts: { label: 'Subcuentas', path: '/cardcloud/subaccounts', section: 'cardcloud', all: ['cardcloud.subaccounts.read-list'] },
    cardholderCards: { label: 'Tarjetas', path: '/cardholders/cards', section: 'tarjetahabiente', all: ['cardholder.cards.read-list'] },
    cardholderVehicles: { label: 'Vehículos', path: '/cardholders/vehicles', section: 'tarjetahabiente', all: ['cardholder.vehicles.read-list'] },
    cardholderWork: { label: 'Trabajo', path: '/cardholders/work', section: 'tarjetahabiente', all: ['cardholder.sub-companies.read-one'] },
    documents: { label: 'Documentos', path: '/documents', section: 'documentos', all: ['documents.module'] },
} as const satisfies Record<string, SidebarCapabilityDefinition>;

export const MODULE_CAPABILITIES = {
    dashboard: {
        canEnter: { authenticated: true },
        permissions: [],
        actions: {
            read: { authenticated: true },
        },
    },

    users: {
        canEnter: { all: ['users.module'] },
        permissions: [
            'users.module',
            'users.create',
            'users.read-list',
            'users.read-one',
            'users.update',
            'users.delete',
            'users.access.assign',
            'users.access.read',
            'users.permissions.read',
            'users.password.update',
            'users.2fa.unlink',
            'users.credentials.resend',
        ],
        actions: {
            openCreate: { all: ['users.create'] },
            create: { all: ['users.create'] },
            refreshList: { all: ['users.read-list'] },
            readList: { all: ['users.read-list'] },
            configureColumns: { all: ['users.read-list'] },
            exportList: { all: ['users.read-list'] },
            openDetail: { all: ['users.read-one'] },
            openDetailDrawer: { all: ['users.read-one'] },
            readOne: { all: ['users.read-one'] },
            openEdit: { all: ['users.update'] },
            openEditModal: { all: ['users.update'] },
            update: { all: ['users.update'] },
            openAccess: { any: ['users.access.read', 'users.access.assign'] },
            openAccessModal: { any: ['users.access.read', 'users.access.assign'] },
            readAccess: { all: ['users.access.read'] },
            assignAccess: { all: ['users.access.assign'] },
            replaceAccess: { all: ['users.access.assign'] },
            removeAccess: { all: ['users.access.assign'] },
            openPermissions: { all: ['users.permissions.read'] },
            openPermissionsTab: { all: ['users.permissions.read'] },
            readPermissions: { all: ['users.permissions.read'] },
            openChangePassword: { all: ['users.password.update'] },
            openChangePasswordModal: { all: ['users.password.update'] },
            changePassword: { all: ['users.password.update'] },
            openUnlinkTwoFactor: { all: ['users.2fa.unlink'] },
            openUnlinkTwoFactorModal: { all: ['users.2fa.unlink'] },
            unlinkTwoFactor: { all: ['users.2fa.unlink'] },
            openResendCredentials: { all: ['users.credentials.resend'] },
            openResendCredentialsModal: { all: ['users.credentials.resend'] },
            resendCredentials: { all: ['users.credentials.resend'] },
        },
    },

    roles: {
        canEnter: { all: ['roles.module'] },
        permissions: ['roles.module', 'roles.create', 'roles.read-list', 'roles.read-one', 'roles.update', 'roles.delete', 'roles.permissions.assign', 'roles.permissions.read'],
        actions: {
            openCreate: { all: ['roles.create'] },
            create: { all: ['roles.create'] },
            refreshList: { all: ['roles.read-list'] },
            readList: { all: ['roles.read-list'] },
            configureColumns: { all: ['roles.read-list'] },
            exportList: { all: ['roles.read-list'] },
            openDetail: { all: ['roles.read-one'] },
            openDetailDrawer: { all: ['roles.read-one'] },
            readOne: { all: ['roles.read-one'] },
            openEdit: { all: ['roles.update'] },
            openEditDrawer: { all: ['roles.update'] },
            update: { all: ['roles.update'] },
            openDelete: { all: ['roles.delete'] },
            openDeleteDialog: { all: ['roles.delete'] },
            delete: { all: ['roles.delete'] },
            openPermissions: { any: ['roles.permissions.read', 'roles.permissions.assign'] },
            openPermissionsTab: { any: ['roles.permissions.read', 'roles.permissions.assign'] },
            readPermissions: { all: ['roles.permissions.read'] },
            assignPermissions: { all: ['roles.permissions.assign'] },
            replacePermissions: { all: ['roles.permissions.assign'] },
        },
    },

    permissions: {
        canEnter: { all: ['permissions.module'] },
        permissions: ['permissions.module', 'permissions.create', 'permissions.read-list', 'permissions.read-one', 'permissions.update', 'permissions.delete'],
        actions: {
            refreshList: { all: ['permissions.read-list'] },
            readList: { all: ['permissions.read-list'] },
            configureColumns: { all: ['permissions.read-list'] },
            exportList: { all: ['permissions.read-list'] },
            openDetail: { all: ['permissions.read-one'] },
            readOne: { all: ['permissions.read-one'] },
        },
    },

    companies: {
        canEnter: { all: ['companies.module'] },
        permissions: ['companies.module', 'companies.create', 'companies.read-list', 'companies.read-one', 'companies.update', 'companies.delete'],
        actions: {
            openCreate: { all: ['companies.create'] },
            openCreateForm: { all: ['companies.create'] },
            openCreateAddress: { all: ['companies.create'] },
            create: { all: ['companies.create'] },
            refreshList: { all: ['companies.read-list'] },
            readList: { all: ['companies.read-list'] },
            configureColumns: { all: ['companies.read-list'] },
            exportList: { all: ['companies.read-list'] },
            openDetail: { all: ['companies.read-one'] },
            openDetailDrawer: { all: ['companies.read-one'] },
            openDetailForm: { all: ['companies.read-one'] },
            openDetailAddress: { all: ['companies.read-one'] },
            readOne: { all: ['companies.read-one'] },
            openEdit: { all: ['companies.update'] },
            openEditDrawer: { all: ['companies.update'] },
            openEditForm: { all: ['companies.update'] },
            openEditAddress: { all: ['companies.update'] },
            update: { all: ['companies.update'] },
            openDeactivate: { all: ['companies.delete'] },
            openDeactivateDialog: { all: ['companies.delete'] },
            deactivate: { all: ['companies.delete'] },
            delete: { all: ['companies.delete'] },
        },
    },

    subCompanies: {
        canEnter: { all: ['sub-companies.module'] },
        permissions: [
            'sub-companies.module',
            'sub-companies.create',
            'sub-companies.read-list',
            'sub-companies.read-one',
            'sub-companies.update',
            'sub-companies.delete',
            'drivers.download',
            'vehicles.download',
            'cards.download',
        ],
        actions: {
            openCreate: { all: ['sub-companies.create'] },
            openCreateForm: { all: ['sub-companies.create'] },
            openCreateAddress: { all: ['sub-companies.create'] },
            create: { all: ['sub-companies.create'] },
            refreshList: { all: ['sub-companies.read-list'] },
            readList: { all: ['sub-companies.read-list'] },
            configureColumns: { all: ['sub-companies.read-list'] },
            exportList: { all: ['sub-companies.read-list'] },
            openDetail: { all: ['sub-companies.read-one'] },
            openDetailDrawer: { all: ['sub-companies.read-one'] },
            openDetailForm: { all: ['sub-companies.read-one'] },
            openDetailAddress: { all: ['sub-companies.read-one'] },
            readOne: { all: ['sub-companies.read-one'] },
            openEdit: { all: ['sub-companies.update'] },
            openEditDrawer: { all: ['sub-companies.update'] },
            openEditForm: { all: ['sub-companies.update'] },
            openEditAddress: { all: ['sub-companies.update'] },
            update: { all: ['sub-companies.update'] },
            openDeactivate: { all: ['sub-companies.delete'] },
            openDeactivateDialog: { all: ['sub-companies.delete'] },
            deactivate: { all: ['sub-companies.delete'] },
            delete: { all: ['sub-companies.delete'] },
            openRelatedData: { any: ['drivers.download', 'vehicles.download', 'cards.download'] },
            openRelatedDrivers: { all: ['drivers.download'] },
            openRelatedVehicles: { all: ['vehicles.download'] },
            openRelatedCards: { all: ['cards.download'] },
            searchRelatedDrivers: { all: ['drivers.download'] },
            searchRelatedVehicles: { all: ['vehicles.download'] },
            searchRelatedCards: { all: ['cards.download'] },
            downloadDrivers: { all: ['drivers.download'] },
            downloadVehicles: { all: ['vehicles.download'] },
            downloadCards: { all: ['cards.download'] },
        },
    },

    drivers: {
        canEnter: { all: ['drivers.module'] },
        permissions: [
            'drivers.module',
            'drivers.create',
            'drivers.read-list',
            'drivers.read-one',
            'drivers.vehicles.read-list',
            'drivers.download',
            'drivers.update',
            'drivers.delete',
            'sub-companies.read-list',
            'users.read-list',
        ],
        actions: {
            openCreate: { all: ['drivers.create'] },
            openCreateForm: { all: ['drivers.create'] },
            openCreateAddress: { all: ['drivers.create'] },
            create: { all: ['drivers.create'] },
            openSubCompanySelect: { all: ['sub-companies.read-list'] },
            openLinkedUserSelect: { all: ['users.read-list'] },
            refreshList: { all: ['drivers.read-list'] },
            readList: { all: ['drivers.read-list'] },
            configureColumns: { all: ['drivers.read-list'] },
            exportList: { all: ['drivers.read-list'] },
            openDetail: { all: ['drivers.read-one'] },
            openDetailDrawer: { all: ['drivers.read-one'] },
            openDetailForm: { all: ['drivers.read-one'] },
            openDetailAddress: { all: ['drivers.read-one'] },
            readOne: { all: ['drivers.read-one'] },
            openVehicles: { all: ['drivers.vehicles.read-list'] },
            openVehiclesDrawer: { all: ['drivers.vehicles.read-list'] },
            readVehicles: { all: ['drivers.vehicles.read-list'] },
            searchVehicles: { all: ['drivers.vehicles.read-list'] },
            exportVehicles: { all: ['drivers.vehicles.read-list'] },
            download: { all: ['drivers.download'] },
            openEdit: { all: ['drivers.update'] },
            openEditDrawer: { all: ['drivers.update'] },
            openEditForm: { all: ['drivers.update'] },
            openEditAddress: { all: ['drivers.update'] },
            update: { all: ['drivers.update'] },
            openDeactivate: { all: ['drivers.delete'] },
            openDeactivateDialog: { all: ['drivers.delete'] },
            deactivate: { all: ['drivers.delete'] },
            delete: { all: ['drivers.delete'] },
        },
    },

    vehicles: {
        canEnter: { all: ['vehicles.module'] },
        permissions: [
            'vehicles.module',
            'vehicles.create',
            'vehicles.read-list',
            'vehicles.read-one',
            'vehicles.drivers.read-list',
            'vehicles.download',
            'vehicles.update',
            'vehicles.driver.assign',
            'vehicles.delete',
            'sub-companies.read-list',
            'fuels.read-list',
            'drivers.read-list',
        ],
        actions: {
            openCreate: { all: ['vehicles.create'] },
            create: { all: ['vehicles.create'] },
            openSubCompanySelect: { all: ['sub-companies.read-list'] },
            openFuelSelect: { all: ['fuels.read-list'] },
            openDriverSelect: { all: ['drivers.read-list'] },
            refreshList: { all: ['vehicles.read-list'] },
            readList: { all: ['vehicles.read-list'] },
            configureColumns: { all: ['vehicles.read-list'] },
            exportList: { all: ['vehicles.read-list'] },
            openDetail: { all: ['vehicles.read-one'] },
            openDetailDialog: { all: ['vehicles.read-one'] },
            readOne: { all: ['vehicles.read-one'] },
            openCurrentDriver: { all: ['vehicles.drivers.read-list'] },
            openCurrentDriverDialog: { all: ['vehicles.drivers.read-list'] },
            readDrivers: { all: ['vehicles.drivers.read-list'] },
            searchDrivers: { all: ['vehicles.drivers.read-list'] },
            download: { all: ['vehicles.download'] },
            openEdit: { all: ['vehicles.update'] },
            openEditDialog: { all: ['vehicles.update'] },
            update: { all: ['vehicles.update'] },
            openAssignDriver: { all: ['vehicles.driver.assign'] },
            openAssignDriverDialog: { all: ['vehicles.driver.assign'] },
            assignDriver: { all: ['vehicles.driver.assign'] },
            unassignDriver: { all: ['vehicles.driver.assign'] },
            openDeactivate: { all: ['vehicles.delete'] },
            openDeactivateDialog: { all: ['vehicles.delete'] },
            deactivate: { all: ['vehicles.delete'] },
            delete: { all: ['vehicles.delete'] },
        },
    },

    cards: {
        canEnter: { all: ['cards.module'] },
        permissions: [
            'cards.module',
            'cards.create',
            'cards.read-list',
            'cards.read-one',
            'cards.design-fuel.read',
            'cards.download',
            'cards.validate',
            'cards.movements.read-list',
            'cards.sync',
            'cards.update',
            'cards.assignment.update',
            'cards.vehicle.assign',
            'cards.unassign',
            'cards.delete',
            'vehicles.read-list',
            'sub-companies.read-list',
            'fuels.read-list',
            'cardcloud-stock.sub-company.assign',
        ],
        actions: {
            refreshList: { all: ['cards.read-list'] },
            readList: { all: ['cards.read-list'] },
            configureColumns: { all: ['cards.read-list'] },
            exportList: { all: ['cards.download'] },
            download: { all: ['cards.download'] },
            openDetail: { all: ['cards.read-one'] },
            openDetailDialog: { all: ['cards.read-one'] },
            readOne: { all: ['cards.read-one'] },
            openMovements: { all: ['cards.movements.read-list'] },
            openMovementsDrawer: { all: ['cards.movements.read-list'] },
            readMovements: { all: ['cards.movements.read-list'] },
            filterMovements: { all: ['cards.movements.read-list'] },
            exportMovements: { all: ['cards.movements.read-list'] },
            openAssignVehicle: { all: ['cards.vehicle.assign'] },
            openAssignVehicleDialog: { all: ['cards.vehicle.assign'] },
            openVehicleSelect: { all: ['vehicles.read-list'] },
            assignVehicle: { all: ['cards.vehicle.assign'] },
            openUnassign: { all: ['cards.unassign'] },
            openUnassignDialog: { all: ['cards.unassign'] },
            unassign: { all: ['cards.unassign'] },
            openEdit: { all: ['cards.update'] },
            openEditDrawer: { all: ['cards.update'] },
            update: { all: ['cards.update'] },
            updateAssignment: { all: ['cards.assignment.update'] },
            openDeactivate: { all: ['cards.delete'] },
            openDeactivateDialog: { all: ['cards.delete'] },
            deactivate: { all: ['cards.delete'] },
            delete: { all: ['cards.delete'] },
            openSubCompanySelect: { all: ['sub-companies.read-list'] },
            openFuelSelect: { all: ['fuels.read-list'] },
            readByDesignFuel: { all: ['cards.design-fuel.read'] },
            openManualCreate: { all: ['cards.create'] },
            create: { all: ['cards.create'] },
            openValidate: { all: ['cards.validate'] },
            validate: { all: ['cards.validate'] },
            openSyncSubCompany: { all: ['cards.sync'] },
            syncSubCompany: { all: ['cards.sync'] },
            sync: { all: ['cards.sync'] },
            openAssignCardcloud: { all: ['cardcloud-stock.sub-company.assign'] },
            assignCardcloud: { all: ['cardcloud-stock.sub-company.assign'] },
            downloadAssignCardcloudTemplate: { all: ['cardcloud-stock.sub-company.assign'] },
            uploadAssignCardcloudExcel: { all: ['cardcloud-stock.sub-company.assign'] },
        },
    },

    fuels: {
        canEnter: { all: ['fuels.module'] },
        permissions: ['fuels.module', 'fuels.create', 'fuels.read-list', 'fuels.read-one', 'fuels.update', 'fuels.delete'],
        actions: {
            openCreate: { all: ['fuels.create'] },
            openCreateDialog: { all: ['fuels.create'] },
            create: { all: ['fuels.create'] },
            refreshList: { all: ['fuels.read-list'] },
            readList: { all: ['fuels.read-list'] },
            configureColumns: { all: ['fuels.read-list'] },
            exportList: { all: ['fuels.read-list'] },
            openDetail: { all: ['fuels.read-one'] },
            openDetailDialog: { all: ['fuels.read-one'] },
            readOne: { all: ['fuels.read-one'] },
            openEdit: { all: ['fuels.update'] },
            openEditDialog: { all: ['fuels.update'] },
            update: { all: ['fuels.update'] },
            openDeactivate: { all: ['fuels.delete'] },
            openDeactivateDialog: { all: ['fuels.delete'] },
            deactivate: { all: ['fuels.delete'] },
            delete: { all: ['fuels.delete'] },
        },
    },

    stations: {
        canEnter: { all: ['stations.module'] },
        permissions: [
            'stations.module',
            'stations.create',
            'stations.read-list',
            'stations.read-one',
            'stations.update',
            'stations.delete',
            'sub-companies.read-list',
            'station-fuels.read-list',
            'station-fuels.create',
            'station-fuels.update',
            'station-fuels.delete',
        ],
        actions: {
            openCreate: { all: ['stations.create'] },
            openCreateDrawer: { all: ['stations.create'] },
            openCreateForm: { all: ['stations.create'] },
            openCreateAddress: { all: ['stations.create'] },
            create: { all: ['stations.create'] },
            openSubCompanySelect: { all: ['sub-companies.read-list'] },
            refreshList: { all: ['stations.read-list'] },
            readList: { all: ['stations.read-list'] },
            configureColumns: { all: ['stations.read-list'] },
            exportList: { all: ['stations.read-list'] },
            openDetail: { all: ['stations.read-one'] },
            openDetailDrawer: { all: ['stations.read-one'] },
            openDetailForm: { all: ['stations.read-one'] },
            openDetailAddress: { all: ['stations.read-one'] },
            readOne: { all: ['stations.read-one'] },
            openAvailableFuels: { all: ['station-fuels.read-list'] },
            openAvailableFuelsDrawer: { all: ['station-fuels.read-list'] },
            readAvailableFuels: { all: ['station-fuels.read-list'] },
            openAddFuel: { all: ['station-fuels.create'] },
            addFuel: { all: ['station-fuels.create'] },
            updateAvailableFuel: { all: ['station-fuels.update'] },
            removeAvailableFuel: { all: ['station-fuels.delete'] },
            openEdit: { all: ['stations.update'] },
            openEditDrawer: { all: ['stations.update'] },
            openEditForm: { all: ['stations.update'] },
            openEditAddress: { all: ['stations.update'] },
            update: { all: ['stations.update'] },
            openDeactivate: { all: ['stations.delete'] },
            openDeactivateDialog: { all: ['stations.delete'] },
            deactivate: { all: ['stations.delete'] },
            delete: { all: ['stations.delete'] },
        },
    },

    stationFuels: {
        canEnter: { all: ['station-fuels.module'] },
        permissions: ['station-fuels.module', 'station-fuels.create', 'station-fuels.read-list', 'station-fuels.read-one', 'station-fuels.update', 'station-fuels.delete'],
        actions: {
            openCreate: { all: ['station-fuels.create'] },
            openCreateDialog: { all: ['station-fuels.create'] },
            create: { all: ['station-fuels.create'] },
            refreshList: { all: ['station-fuels.read-list'] },
            readList: { all: ['station-fuels.read-list'] },
            openDetail: { all: ['station-fuels.read-one'] },
            readOne: { all: ['station-fuels.read-one'] },
            openEdit: { all: ['station-fuels.update'] },
            openEditDialog: { all: ['station-fuels.update'] },
            update: { all: ['station-fuels.update'] },
            openDeactivate: { all: ['station-fuels.delete'] },
            openDeactivateDialog: { all: ['station-fuels.delete'] },
            deactivate: { all: ['station-fuels.delete'] },
            delete: { all: ['station-fuels.delete'] },
        },
    },

    cardcloudAccount: {
        canEnter: { all: ['cardcloud.account.read-one'] },
        permissions: ['cardcloud.module', 'cardcloud.account.read-one', 'cardcloud.account.movements.read-list'],
        actions: {
            openAccountTab: { all: ['cardcloud.account.read-one'] },
            readOne: { all: ['cardcloud.account.read-one'] },
            refreshAccount: { all: ['cardcloud.account.read-one'] },
            openMovementsTab: { all: ['cardcloud.account.movements.read-list'] },
            readMovements: { all: ['cardcloud.account.movements.read-list'] },
            filterMovements: { all: ['cardcloud.account.movements.read-list'] },
            clearMovementFilters: { all: ['cardcloud.account.movements.read-list'] },
            consultMovements: { all: ['cardcloud.account.movements.read-list'] },
            exportMovements: { all: ['cardcloud.account.movements.read-list'] },
        },
    },

    cardcloudStock: {
        canEnter: { all: ['cardcloud-stock.module'] },
        permissions: [
            'cardcloud-stock.module',
            'cardcloud-stock.read-list',
            'cardcloud-stock.sync',
            'cardcloud-stock.sub-company.assign',
            'cardcloud-stock.sub-company.unassign',
            'sub-companies.read-list',
        ],
        actions: {
            refreshList: { all: ['cardcloud-stock.read-list'] },
            readList: { all: ['cardcloud-stock.read-list'] },
            configureColumns: { all: ['cardcloud-stock.read-list'] },
            exportList: { all: ['cardcloud-stock.read-list'] },
            openDetail: { all: ['cardcloud-stock.read-list'] },
            openDetailDialog: { all: ['cardcloud-stock.read-list'] },
            openSync: { all: ['cardcloud-stock.sync'] },
            sync: { all: ['cardcloud-stock.sync'] },
            openAssignSubCompany: { all: ['cardcloud-stock.sub-company.assign'] },
            openAssignSubCompanyDialog: { all: ['cardcloud-stock.sub-company.assign'] },
            openAssignSubCompanyExcel: { all: ['cardcloud-stock.sub-company.assign'] },
            downloadAssignSubCompanyTemplate: { all: ['cardcloud-stock.sub-company.assign'] },
            uploadAssignSubCompanyExcel: { all: ['cardcloud-stock.sub-company.assign'] },
            openSubCompanySelect: { all: ['sub-companies.read-list'] },
            assignSubCompany: { all: ['cardcloud-stock.sub-company.assign'] },
            openUnassignSubCompany: { all: ['cardcloud-stock.sub-company.unassign'] },
            openUnassignSubCompanyDialog: { all: ['cardcloud-stock.sub-company.unassign'] },
            unassignSubCompany: { all: ['cardcloud-stock.sub-company.unassign'] },
        },
    },

    cardcloudTransfers: {
        canEnter: { any: ['cardcloud.account.transfer', 'cardcloud.account.transfer.bulk'] },
        permissions: ['cardcloud.module', 'cardcloud.account.transfer', 'cardcloud.account.transfer.bulk'],
        actions: {
            transfer: { all: ['cardcloud.account.transfer'] },
            transferBulk: { all: ['cardcloud.account.transfer.bulk'] },
            downloadTemplate: { all: ['cardcloud.account.transfer.bulk'] },
            uploadExcel: { all: ['cardcloud.account.transfer.bulk'] },
        },
    },

    cardcloudSubaccounts: {
        canEnter: { all: ['cardcloud.subaccounts.read-list'] },
        permissions: [
            'cardcloud.module',
            'cardcloud.subaccounts.read-list',
            'cardcloud.subaccounts.read-one',
            'cardcloud.subaccounts.cards.read-list',
            'cardcloud.subaccounts.create',
            'cardcloud.subaccounts.movements.read-list',
        ],
        actions: {
            refreshList: { all: ['cardcloud.subaccounts.read-list'] },
            readList: { all: ['cardcloud.subaccounts.read-list'] },
            configureColumns: { all: ['cardcloud.subaccounts.read-list'] },
            exportList: { all: ['cardcloud.subaccounts.read-list'] },
            openDetail: { all: ['cardcloud.subaccounts.read-one'] },
            openDetailDrawer: { all: ['cardcloud.subaccounts.read-one'] },
            openDetailTab: { all: ['cardcloud.subaccounts.read-one'] },
            readOne: { all: ['cardcloud.subaccounts.read-one'] },
            openCardsTab: { all: ['cardcloud.subaccounts.cards.read-list'] },
            readCards: { all: ['cardcloud.subaccounts.cards.read-list'] },
            searchCards: { all: ['cardcloud.subaccounts.cards.read-list'] },
            exportCards: { all: ['cardcloud.subaccounts.cards.read-list'] },
            openCreate: { all: ['cardcloud.subaccounts.create'] },
            create: { all: ['cardcloud.subaccounts.create'] },
            openMovementsTab: { all: ['cardcloud.subaccounts.movements.read-list'] },
            readMovements: { all: ['cardcloud.subaccounts.movements.read-list'] },
            filterMovements: { all: ['cardcloud.subaccounts.movements.read-list'] },
            clearMovementFilters: { all: ['cardcloud.subaccounts.movements.read-list'] },
            exportMovements: { all: ['cardcloud.subaccounts.movements.read-list'] },
        },
    },

    cardcloudCards: {
        canEnter: { all: ['cardcloud.cards.read-one'] },
        permissions: [
            'cardcloud.module',
            'cardcloud.cards.read-one',
            'cardcloud.cards.movements.read-list',
            'cardcloud.cards.movements.read-one',
            'cardcloud.cards.sensitive.read-one',
            'cardcloud.cards.cvv.read',
            'cardcloud.cards.nip.update',
            'cardcloud.cards.validate',
            'cardcloud.cards.block',
            'cardcloud.cards.unblock',
            'cardcloud.cards.assign',
            'cardcloud.cards.assign.bulk',
        ],
        actions: {
            openDetail: { all: ['cardcloud.cards.read-one'] },
            openDetailRoute: { all: ['cardcloud.cards.read-one'] },
            readOne: { all: ['cardcloud.cards.read-one'] },
            openMovementsSection: { all: ['cardcloud.cards.movements.read-list'] },
            readMovements: { all: ['cardcloud.cards.movements.read-list'] },
            filterMovements: { all: ['cardcloud.cards.movements.read-list'] },
            clearMovementFilters: { all: ['cardcloud.cards.movements.read-list'] },
            exportMovements: { all: ['cardcloud.cards.movements.read-list'] },
            openMovementDetail: { all: ['cardcloud.cards.movements.read-one'] },
            readMovement: { all: ['cardcloud.cards.movements.read-one'] },
            readSensitive: { all: ['cardcloud.cards.sensitive.read-one'] },
            readCvv: { all: ['cardcloud.cards.cvv.read'] },
            updateNip: { all: ['cardcloud.cards.nip.update'] },
            validate: { all: ['cardcloud.cards.validate'] },
            block: { all: ['cardcloud.cards.block'] },
            unblock: { all: ['cardcloud.cards.unblock'] },
            assign: { all: ['cardcloud.cards.assign'] },
            assignBulk: { all: ['cardcloud.cards.assign.bulk'] },
        },
    },

    cardholder: {
        canEnter: { all: ['cardholder.module'] },
        permissions: [
            'cardholder.module',
            'cardholder.profile.read',
            'cardholder.sub-companies.read-one',
            'cardholder.vehicles.read-list',
            'cardholder.cards.read-list',
            'cardholder.cards.read-one',
            'cardholder.cards.movements.read-list',
            'cardholder.cards.sensitive.read-one',
            'cardholder.cards.nip.update',
            'cardholder.cards.power.off',
            'cardholder.cards.power.on',
            'cardholder.cards.validate',
        ],
        actions: {
            openProfile: { all: ['cardholder.profile.read'] },
            readProfile: { all: ['cardholder.profile.read'] },
            openSubCompany: { all: ['cardholder.sub-companies.read-one'] },
            readSubCompany: { all: ['cardholder.sub-companies.read-one'] },
            openVehicles: { all: ['cardholder.vehicles.read-list'] },
            readVehicles: { all: ['cardholder.vehicles.read-list'] },
            openCards: { all: ['cardholder.cards.read-list'] },
            readCards: { all: ['cardholder.cards.read-list'] },
            openCardDetail: { all: ['cardholder.cards.read-one'] },
            readCard: { all: ['cardholder.cards.read-one'] },
            openCardMovements: { all: ['cardholder.cards.movements.read-list'] },
            readCardMovements: { all: ['cardholder.cards.movements.read-list'] },
            readMovements: { all: ['cardholder.cards.movements.read-list'] },
            openSensitiveData: { all: ['cardholder.cards.sensitive.read-one'] },
            readSensitiveData: { all: ['cardholder.cards.sensitive.read-one'] },
            readSensitive: { all: ['cardholder.cards.sensitive.read-one'] },
            openChangeNip: { all: ['cardholder.cards.nip.update'] },
            updateNip: { all: ['cardholder.cards.nip.update'] },
            openPowerOff: { all: ['cardholder.cards.power.off'] },
            powerOff: { all: ['cardholder.cards.power.off'] },
            openPowerOn: { all: ['cardholder.cards.power.on'] },
            powerOn: { all: ['cardholder.cards.power.on'] },
            openValidateCard: { all: ['cardholder.cards.validate'] },
            validateCard: { all: ['cardholder.cards.validate'] },
            validate: { all: ['cardholder.cards.validate'] },
        },
    },

    cardholderCards: {
        canEnter: { all: ['cardholder.cards.read-list'] },
        permissions: [
            'cardholder.cards.read-list',
            'cardholder.cards.read-one',
            'cardholder.cards.movements.read-list',
            'cardholder.cards.sensitive.read-one',
            'cardholder.cards.nip.update',
            'cardholder.cards.power.off',
            'cardholder.cards.power.on',
            'cardholder.cards.validate',
        ],
        actions: {
            readList: { all: ['cardholder.cards.read-list'] },
            openValidateCard: { all: ['cardholder.cards.validate'] },
            validateCard: { all: ['cardholder.cards.validate'] },
            openDetail: { all: ['cardholder.cards.read-one'] },
            readOne: { all: ['cardholder.cards.read-one'] },
            openMovements: { all: ['cardholder.cards.movements.read-list'] },
            readMovements: { all: ['cardholder.cards.movements.read-list'] },
            openSensitiveData: { all: ['cardholder.cards.sensitive.read-one'] },
            readSensitiveData: { all: ['cardholder.cards.sensitive.read-one'] },
            openChangeNip: { all: ['cardholder.cards.nip.update'] },
            updateNip: { all: ['cardholder.cards.nip.update'] },
            openPowerOff: { all: ['cardholder.cards.power.off'] },
            powerOff: { all: ['cardholder.cards.power.off'] },
            openPowerOn: { all: ['cardholder.cards.power.on'] },
            powerOn: { all: ['cardholder.cards.power.on'] },
        },
    },

    cardholderVehicles: {
        canEnter: { all: ['cardholder.vehicles.read-list'] },
        permissions: ['cardholder.vehicles.read-list'],
        actions: {
            readList: { all: ['cardholder.vehicles.read-list'] },
        },
    },

    cardholderWork: {
        canEnter: { all: ['cardholder.sub-companies.read-one'] },
        permissions: ['cardholder.sub-companies.read-one'],
        actions: {
            readOne: { all: ['cardholder.sub-companies.read-one'] },
        },
    },

    cardholders: {
        canEnter: { all: ['cardholders.module'] },
        permissions: ['cardholders.module', 'cardholders.read-list', 'sub-companies.read-list'],
        actions: {
            refreshList: { all: ['cardholders.read-list'] },
            readList: { all: ['cardholders.read-list'] },
            configureColumns: { all: ['cardholders.read-list'] },
            exportList: { all: ['cardholders.read-list'] },
            openSubCompanyFilter: { all: ['sub-companies.read-list'] },
            filterPendingSetup: { all: ['cardholders.read-list'] },
            openDetail: { all: ['cardholders.read-list'] },
            openDetailDrawer: { all: ['cardholders.read-list'] },
        },
    },

    documents: {
        canEnter: { all: ['documents.module'] },
        permissions: ['documents.module', 'documents.create', 'documents.read-list', 'documents.read-one', 'documents.download', 'documents.update', 'documents.delete', 'sub-companies.read-list'],
        actions: {
            openCreate: { all: ['documents.create'] },
            create: { all: ['documents.create'] },
            refreshList: { all: ['documents.read-list'] },
            readList: { all: ['documents.read-list'] },
            configureColumns: { all: ['documents.read-list'] },
            exportList: { all: ['documents.read-list'] },
            openSubCompanySelect: { all: ['sub-companies.read-list'] },
            openDetail: { all: ['documents.read-one'] },
            openDetailDialog: { all: ['documents.read-one'] },
            readOne: { all: ['documents.read-one'] },
            download: { all: ['documents.download'] },
            openEdit: { all: ['documents.update'] },
            openEditDialog: { all: ['documents.update'] },
            update: { all: ['documents.update'] },
            openDelete: { all: ['documents.delete'] },
            openDeleteDialog: { all: ['documents.delete'] },
            delete: { all: ['documents.delete'] },
        },
    },

    notifications: {
        canEnter: { all: ['notifications.module'] },
        permissions: ['notifications.module', 'notifications.create', 'notifications.read-list', 'notifications.unread-count.read', 'notifications.mark-read', 'notifications.mark-read-all'],
        actions: {
            openBell: { all: ['notifications.unread-count.read'] },
            showBadge: { all: ['notifications.unread-count.read'] },
            refreshUnreadCount: { all: ['notifications.unread-count.read'] },
            openInboxPopover: { all: ['notifications.read-list'] },
            openInboxDrawer: { all: ['notifications.read-list'] },
            create: { all: ['notifications.create'] },
            readList: { all: ['notifications.read-list'] },
            readUnreadCount: { all: ['notifications.unread-count.read'] },
            openNotification: { all: ['notifications.mark-read'] },
            markRead: { all: ['notifications.mark-read'] },
            openMarkAllRead: { all: ['notifications.mark-read-all'] },
            markReadAll: { all: ['notifications.mark-read-all'] },
            openAdminCreate: { all: ['notifications.create'] },
        },
    },

    audit: {
        canEnter: { all: ['audit.module'] },
        permissions: ['audit.module', 'audit.read-list', 'audit.read-one'],
        actions: {
            readList: { all: ['audit.read-list'] },
            readOne: { all: ['audit.read-one'] },
            openRequestsTab: { all: ['audit.read-list'] },
            readRequests: { all: ['audit.read-list'] },
            openSecurityTab: { all: ['audit.read-list'] },
            readSecurity: { all: ['audit.read-list'] },
            openAccessTab: { all: ['audit.read-list'] },
            readAccess: { all: ['audit.read-list'] },
            openBusinessTab: { all: ['audit.read-list'] },
            readBusiness: { all: ['audit.read-list'] },
            openCardsTab: { all: ['audit.read-list'] },
            readCards: { all: ['audit.read-list'] },
            openCardcloudTab: { all: ['audit.read-list'] },
            readCardcloud: { all: ['audit.read-list'] },
            openTransfersTab: { all: ['audit.read-list'] },
            readTransfers: { all: ['audit.read-list'] },
            openCardAssignmentsTab: { all: ['audit.read-list'] },
            readCardAssignments: { all: ['audit.read-list'] },
            filterList: { all: ['audit.read-list'] },
            configureColumns: { all: ['audit.read-list'] },
            exportList: { all: ['audit.read-list'] },
            openDetail: { all: ['audit.read-one'] },
        },
    },
} as const satisfies Record<string, ModuleCapabilityDefinition>;
